### ISSUE TITLE
Don't rely on force push

### ISSUE THREAD

**Issue by lewisf** [kadirahq/storybook-deployer#12]
Hey @arunoda 

Our organization has strict requirements to not allow force pushing on any repositories, mostly because it generally isn't a good thing for us.

What are your thoughts on using a merge/rebase flow instead of force pushing?

**Comment by lewisf** [comment]
Doing it like: https://github.com/blog/2228-simpler-github-pages-publishing might work as well. Is that something that we can do with storybook-deployer?

**Comment by arunoda** [comment]
@lewisf for that, you don't need this at all. Simply use a npm script to build storybook into that directory.

For this tool, force push is necessary. So, I am gonna close this.

**Comment by CpuID** [comment]
😢

**Comment by jhirbour** [comment]
using `force-with-lease` would at least be safer.

http://weiqingtoh.github.io/force-with-lease/
