### ISSUE TITLE
loading fonts and images from static folder

### ISSUE THREAD

**Issue by awei01** [kadirahq/storybook-deployer#2]
First of all, great tool. The entire `storybook` suite has made UI dev much, much faster.

Here's my issue: I have some static files (fonts and images) that I need to load in my stories. These work great locally. But, once deployed onto github pages (https://awei01.github.io/sui-stateless-components), `<img src>` references and css `url()` references stop working. 

Specifically an `<img src='/images/foo.png'>` which worked locally now breaks because github pages appends the project name after my github pages url. 

Specific links which illustrate this issue: 
* https://awei01.github.io/sui-stateless-components/?selectedKind=Button&selectedStory=icon&full=0&down=1&left=1&panelRight=0
* https://awei01.github.io/sui-stateless-components/?selectedKind=Image&selectedStory=%3CImage%3E%20default&full=0&down=1&left=1&panelRight=0

Is there a workaround for this issue?

**Comment by awei01** [comment]
ok, sorted out the issue with webpack. not a deployer issue.

**Comment by arpitprod** [comment]
@awei01  How you sorted out? Can you please share webpack code

**Comment by awei01** [comment]
@arpitprod Had to dig around for something that is 4 years old, but I found it: https://github.com/awei01/sui-stateless-components/blob/master/.storybook/webpack.config.js#L21-L35
