### ISSUE TITLE
FR: Generate linked story images

### ISSUE THREAD

**Issue by lorensr** [kadirahq/storybook-deployer#3]
It would be nice if I could generate this section of my readme:

https://github.com/lorensr/segmented-control#component

Images of each story, linked to that story.

**Comment by arunoda** [comment]
You mean get screenshots of each story?

**Comment by lorensr** [comment]
Yes. There are some libraries that can convert html to images, like

- js: https://jsfiddle.net/8ypxW/3/
- ruby: https://github.com/producthunt/ShareMeow

**Comment by arunoda** [comment]
Yep. That's possible and in the plan.
Currently, we can access all the stories in the server side as well.
We'll implement snapshot testing in next week.
So, we can do a doc for this too.

I'm gonna close this now, since this is related to core storybooks package and we are planning to do it soon.
