### ISSUE TITLE
Storybook to GH Pages could be accept parameters

### ISSUE THREAD

**Issue by ceasbz** [kadirahq/storybook-deployer#5]
The script `storybook-to-ghpages` could be accept static folders. 

Like: `storybook-to-ghpages -s ./static/`

**Comment by pedrogustavo** [comment]
:+1:

**Comment by arunoda** [comment]
There's no need for that.
Simply write a `build-storybook` npm script.
See: https://github.com/kadirahq/storybook-deployer#custom-build-configuration

**Comment by ceasbz** [comment]
Hey @arunoda, my idea is to use the `storybook-to-ghpages` exactly to publish the GH Pages. if I use the `build-storybook` need to create a custom script, or not? Because, he just put the files on a output folder. If I'm wrong, let me know :)

**Comment by arunoda** [comment]
I doesn't matter which output directory `build-storybook` has. Create it and try it. It's working and that's what all we use.

**Comment by ceasbz** [comment]
Cool, thanks ;)

**Comment by Maxhodges** [comment]
Hi @arunoda,

We build-storybook to .out with a custom script

```
    "build-storybook": "build-storybook -s ./.meteor/local/build/programs/web.browser/app,./public -o .out"

```

but deploy rebuilds without using our custom build script (no static files are deployed)


```
maxs-imac:blackship maxhodges$ sudo npm run build-storybook
Password:

> blackship-design@ build-storybook /Users/maxhodges/Documents/github/blackship
> build-storybook -s ./.meteor/local/build/programs/web.browser/app,./public -o .out

=> Loading custom addons config.
=> Loading custom webpack config.
=> Copying static files from: ./.meteor/local/build/programs/web.browser/app
=> Copying static files from: ./public
Building storybook ...
maxs-imac:blackship maxhodges$ npm run deploy-storybook

> blackship-design@ deploy-storybook /Users/maxhodges/Documents/github/blackship
> storybook-to-ghpages

=> Getting the git remote URL
   executing: git config --get remote.origin.url
=> Building storybook
   executing: npm run build-storybook -- -o out7393
   executing: git init
   executing: git config user.name "GH Pages Bot"
   executing: git config user.email "hello@ghbot.com"
   executing: git add .
   executing: git commit -m "Deploy Storybook to GitHub Pages"
```

**Comment by arunoda** [comment]
Could you try that with the latest storybook?
We fixed an issue with custom static dirs.
