### ISSUE TITLE
Deploying to GH pages with custom domains

### ISSUE THREAD

**Issue by stipsan** [kadirahq/storybook-deployer#6]
Hey,

In order for custom domains to work I need a CNAME file to be in the root.
This used to work but in the latest release it's added to a static folder, like here:
https://github.com/stipsan/uikit-react/tree/gh-pages/static

So I have to manually move it for it to not break when I publish releases.

**Comment by arunoda** [comment]
Okay do this. Create a [static directory](https://getstorybook.io/docs/configurations/serving-static-files#2-via-a-directory) for storybook. Then put the CNAME file inside that.

**Comment by stipsan** [comment]
Hey, sorry for the late reply!

I have the CNAME here `/.storybook/static/CNAME`.
When the build command runs with `build-storybook -o .out -s .storybook/static` CNAME ends up in `/static/CNAME`. It needs to be in the root on the gh-pages branch for github pages to pick it up, otherwise the custom domain won't be detected by github.

I hope next year you'll make it to React-Next 😄 or maybe on another event? 

Cheers!

**Comment by arunoda** [comment]
@stipsan That's weird. It should be on the root.
Try creating a directory called `public` inside your app and put CNAME inside that.
And use `public` directory for `-s` argument.

**Comment by stipsan** [comment]
If I do that locally using the build storybook command it'll be in /public, not in the root.
It seems like no matter what I do it'll be inside some kind of folder…

Maybe this should have a special case, similar to how head.html is handled?
Whenever this breaks the github site becomes inaccessible as the nameserver points you to the github io server, but with the CNAME file suddenly missing github is unable to recognize what page you're trying to load leading the site to fail to load.

**Comment by arunoda** [comment]
@stipsan we had a bug with the build-storybook command and I just fixed it.
Try to update `@kadira/storybook` to `2.21.0` or higher.

**Comment by stipsan** [comment]
Thanks, I can confirm the problem is fixed! 👍
