### ISSUE TITLE
Deploy custom branch

### ISSUE THREAD

**Issue by TimMikeladze** [kadirahq/storybook-deployer#7]
Accept a parameter to indicating which branch to deploy from. Currently it is hardcoded to master.

**Comment by arunoda** [comment]
Yep. We can even get the current branch dynamically.
Anyway, I'm open to accept any PR for this

**Comment by arunoda** [comment]
I think, I was confused. Storybook deploy the current branch you are in. The one mentioned in the code is the temporary Git repo we are creating.

It's always master.
